### ISSUE TITLE
Add basic analytics

### ISSUE THREAD

**Issue by superdweebie** [biblesoapopera/demo#13]
Add some basic analytics to the demo, driven by ga. Log hits, time on each slide, etc.

Also send the question answers to an email address each time a user completes an episide. Use Mandrill for email integration.

**Comment by superdweebie** [comment]
@90084 I've had a first go at adding some analytics. I've used google, and you are much more experienced with their product than I am, so here are a few things I'd like to take a look at.

* I've created a new ga account to play around with (I'll send you details via private email)
* All the ga stuff for the app is in the one place, you can take a look at the code here: https://github.com/superdweebie/demo/blob/analytics/src/js/analytics.js
* The staging site has been updated with the analytics code, so you can play with it and see the data appear in the ga realtime dashbaord
* At the moment screen changes and question attempts are logged as soon as they occur.
* Regarding data use, adding the ga script has more than doubled the first time download size of the site
* Also regarding data use, each log event uses about 400 bytes

**Comment by 90084** [comment]
Thanks Tim, this is a great step forward.

> I've created a new ga account to play around with (I'll send you details via private email)
great. I've got another GA account that I use for the website, so we might use that eventually, but this is great.
> All the ga stuff for the app is in the one place, you can take a look at the code here: https://github.com/superdweebie/demo/blob/analytics/src/js/analytics.js
> The staging site has been updated with the analytics code, so you can play with it and see the data appear in the ga realtime dashbaord
> At the moment screen changes and question attempts are logged as soon as they occur.
Great.
> Regarding data use, adding the ga script has more than doubled the first time download size of the site
Ouch. Although this shows how small your code is! I'm not worried about this for now.

Thanks,
Martin

**Comment by 90084** [comment]
In time, this will allow us to produce a sample 'dashboard' that we can demo in our pitches - I think this is something that many stakeholders would excited about but wouldn't understand well by me just saying 'we can offer analytics'.

**Comment by superdweebie** [comment]
Marty,
If we want to change GA accounts any time it is very easy to change the ID.

I don't think the download size is a big deal at the moment. Vanilla bso is about 9k, and analytics is about 13k, but will get cached after first load. And some users will already have it cached from other sites.

I like the idea of a dashboard. I think would be worth considering having a dedicated bso analytics server and visualisation tool. I wrote the analytics server for zoop, and I have experimented with web based interactive charting before ...

Are you happy to have this merged into the master as is, or are there some changes that should be made now?

**Comment by 90084** [comment]
> If we want to change GA accounts any time it is very easy to change the ID.
> 
> 
Yep, that's right, no prob.
> I don't think the download size is a big deal at the moment. Vanilla bso is about 9k, and analytics is about 13k, but will get cached after first load. And some users will already have it cached from other sites.
> 
Sure - I'm just impressed with how small your code is.
> I like the idea of a dashboard. I think would be worth considering having a dedicated bso analytics server and visualisation tool. I wrote the analytics server for zoop, and I have experimented with web based interactive charting before ...
> 
Wonderful!
> Are you happy to have this merged into the master as is, or are there some changes that should be made now?
> 
Very happy, thanks.

m

**Comment by superdweebie** [comment]
Closed by #50
