### ISSUE TITLE
Question interaction

### ISSUE THREAD

**Issue by superdweebie** [biblesoapopera/demo#3]
At present the three question slide types (pick, slider, and sort) simply wait for some kind of interaction, and then enable the next button.

Do we need to add functionality for a correct answer?

What should happen if users select a wrong answer?

ping @90084

**Comment by superdweebie** [comment]
@90084 I'm free if you want to give me a call - it's Thursday morning.

**Comment by superdweebie** [comment]
@90084 could you please take a look at the following:

* The new json format that adds scores, multiple question attempts, and feedback. I've tried to make it as simple as possible. Basic doc is here: https://github.com/superdweebie/demo/blob/feedback/docs/slides.json.md. The json for the full demo is here: https://github.com/superdweebie/demo/blob/feedback/data/ep1/slides.json

* An updated version of the demo is here: http://superdweebie.github.io/demo. It contains a few small changes. If you activate the console, then you will see the feedback strings being generated. I haven't added the UI for feedback yet.

Looking forward to your comments and suggestions.

**Comment by 90084** [comment]
> The new json format that adds scores, multiple question attempts, and feedback. I've tried to make it as simple as possible. Basic doc is here: https://github.com/superdweebie/demo/blob/feedback/docs/slides.json.md. The json for the full demo is here: https://github.com/superdweebie/demo/blob/feedback/data/ep1/slides.json
> 
Thanks. 
The 'complete' object felt a bit convoluted to me, but I can see what you're doing. Having an 'allowNext' attribute with a single value of correct|partiallycorrect|always (and defaulting to 'always' or 'correct' if not stated explicitly) is all we need - but I might be missing a scenario you have in mind? It seems the simplest scenario ('always') would require the most text in the current setup.

> An updated version of the demo is here: http://superdweebie.github.io/demo. It contains a few small changes. If you activate the console, then you will see the feedback strings being generated. I haven't added the UI for feedback yet.
> 
The loading bubbles show and nothing else - tried FF and Chrome on OS X. Also Android tablet Chrome.

**Comment by superdweebie** [comment]
I just tried to load the updated demo from my work pc - same problem as you. Will look into it.

I like the suggestion about simplifying the `complete` object. Will do, although I don't think I'll change the name to `allowNext`. I'd like to keep slide idependent from each other if possible, and avoid things that create or imply relationships between them. A slide manages itself, and doesn't know or care about navigation. Navigation is handed at a higher level in the code.

Also, with a another look over the `slides.json` I think we could drop the `author` property. I don't see it having great benefit. And, we should probably add a `series` property so we can have:

```js
{
  "series": "Bible Overview",
  "title": "Episode 1",
  "subtitle": "In the beginning..."
}
```

**Comment by 90084** [comment]
> I like the suggestion about simplifying the complete object. Will do, although I don't think I'll change the name to allowNext. I'd like to keep slide idependent from each other if possible, and avoid things that create or imply relationships between them. A slide manages itself, and doesn't know or care about navigation. Navigation is handed at a higher level in the code.
> 
> 
Yes, agreed, sounds good.
> Also, with a another look over the slides.json I think we could drop the author property. I don't see it having great benefit.
> 
Yes, me neither. 
> And, we should probably add a series property so we can have:
> 
> {
>   "series": "Bible Overview",
>   "title": "Episode 1",
>   "subtitle": "In the beginning..."
> }

Yes, like it.

There's a wider question of inter-episode flow. It would be good to have the ability to restrict going to next episode until current one is 'complete' (for some definition of complete!). Would this be specified in the json? eg conditions for this episode to be played, and a message when it's not met.

**Comment by superdweebie** [comment]
For inter-episode flow I think we need to define a `series.json` that will list the episodes in a series. Then it becomes a question of where to put the `complete` definition. Should it be placed in `series.json` or `slides.json`? I think it probably belongs in `series.json` - we want to be able to determine if the episode is accessble before loading the episode itself.

**Comment by superdweebie** [comment]
I've found and fixed the bug, the link above should work now.

I've also simplified the `complete` property in line with your suggestions.

Regarding inter-episode stuff, I'll ref #12, because that's probably the best place to nut out our ideas.

**Comment by superdweebie** [comment]
@90084 Could you please cast an eye across this link (same as above). I'd like to get your approval before I merge it into Master. I have further work ready to merge waiting on this. Ta

http://superdweebie.github.io/demo

**Comment by 90084** [comment]
All good mate, thanks.
