### ISSUE TITLE
Drop `sections` from episode json

### ISSUE THREAD

**Issue by superdweebie** [biblesoapopera/demo#33]
At present the episode json file allows slides to be grouped into sections. Each section is given a type: listen/discuss/info. They section type is used to define the background coluor of the slide.

I'd like to drop this. Sections add extra complexity, and I am unconviced about their semantic value. However, it does seem to be visually pleasing to have slided of different colours. Perhaps slids could just be given a random background colour?

Thoughts @90084?

**Comment by 90084** [comment]
Happy to drop, I suspect the random colouring might confuse. Happy to have a regular colour...

**Comment by superdweebie** [comment]
Ok. Single colour for now.

**Comment by superdweebie** [comment]
@90084 Also, off topic. I've been developing the list of things to work on and assigning them to different miletones. If you go to the issue list (https://github.com/biblesoapopera/demo/issues) you can filter by milestone and have a browse.

**Comment by 90084** [comment]
Thanks Tim, if I have ideas or notice bugs, you happy for me to just add them here?

**Comment by superdweebie** [comment]
Yes, just create a new issue.

**Comment by superdweebie** [comment]
Closed by #34
