### ISSUE TITLE
Add licence to packages.json

### ISSUE THREAD

**Issue by superdweebie** [biblesoapopera/demo#40]
At the moment NPM gives a warning due to missing licence.

We should really add a licence, especially considering the code is public. So, @90084, what licence should we use?

**Comment by 90084** [comment]
No well informed opinions here. Any suggestions? I'd prefer to start with something more restrictive if possible. GPL might be a good start.
Thanks for bring it up.

**Comment by superdweebie** [comment]
If we want to be restrictive for now, then I don't think we should use any of the common open source licences. Rather I think we should assert that copyright belongs to us (exactly who should be clarified, does copyright belong to me, or you, or BSO?). Then I think we should expicilty say what the software may and may not be used for. eg:

* You may download and use BSO for the purpose of contributing to the development of BSO.
* You may not use BSO code in another software project.

I like the idea of the code being public. Over time we may attract other developers or helpers. However, we don't really want others forking our code profiting from it (unlikely, but possible).

**Comment by 90084** [comment]
> If we want to be restrictive for now, then I don't think we should use any of the common open source licences. Rather I think we should assert that copyright belongs to us
> 
Yes, that's better if possible - I assumed we had to choose from an existing 'open license'.
> (exactly who should be clarified, does copyright belong to me, or you, or BSO?).
> 
It's been all your work so far brother. There's no BSO legal entity to hold the copyright. Once a BSO company/entity is created, it would make sense if all IP (code, scripts) was held there. Until then, it's your call, e.g. just you, or both of us. With our scripts, I've made them copyright myself and Joe (but I've worked on them). If it's copyright you, then it may be wise for you to 'license' me (representing the project) to use it, as silly as that sounds. If/when we come to fundraising, IP clarity would be a factor for many funders I expect.
> Then I think we should expicilty say what the software may and may not be used for. eg:
> 
> You may download and use BSO for the purpose of contributing to the development of BSO.
> You may not use BSO code in another software project.
These two sound fine, although we might not even need to say this. By reserving all rights, anyone interested in using it would be required to contact us first, which is what we want at this stage.
> I like the idea of the code being public. Over time we may attract other developers or helpers.
> 
Yes. I think I want to think more thoroughly the business model of this before we donate the code. 
> However, we don't really want others forking our code profiting from it (unlikely, but possible).
> 
That's right.

m

**Comment by superdweebie** [comment]
Closed by #42
